//! typio-daemon — the Wayland input-method daemon for Typio.
//!
//! ## Current modules
//!
//! - [`engine_loader`] discovers `typio-engine-*.toml` manifests, parses them
//!   with the `toml` crate, negotiates capabilities, and registers
//!   out-of-process engine backends with the Rust runtime.
//! - [`config_watcher`] watches the config directory and engine-manifest
//!   subdirectory via inotify, filters events to relevant files, and debounces
//!   reload triggers with a one-shot timerfd.

// Auto-generated by build.rs: version, install paths, and feature switches.
pub mod build_info {
    include!(concat!(env!("OUT_DIR"), "/build_info.rs"));
}

pub mod app;
pub mod candidate_guard;
pub mod config_watcher;
pub mod diagnostics;
pub mod engine_loader;
pub mod focus_controller;
#[cfg(feature = "systray")]
pub mod icon_badge;
pub mod indicator;
#[cfg(feature = "wayland")]
pub use typio_host_platform::{input_method, panel, panel_shm, protocols, text_raster};
pub mod ipc;
pub mod ipc_bus;
pub mod keyboard;
pub mod keyboard_policy;
pub mod language_display;
pub use typio_host_types::{
    panel_coordinator, panel_present_gate, panel_scheduler, wayland_pending,
};
pub mod preedit;
pub mod repeat_timer;
pub mod resume_signal;
pub(crate) mod runtime;
pub mod service;
pub mod session_glue;
pub mod state_controller;
pub mod text_ui_state;
#[cfg(feature = "systray")]
pub mod tray_menu;
#[cfg(feature = "systray")]
pub mod tray_menu_ids;
#[cfg(feature = "systray")]
pub mod tray_sni;
pub mod uds_server;
#[cfg(feature = "wayland")]
pub mod voice;
