//! typio-host — the Wayland input-method host for Typio.
//!
//! This crate owns the shipping host daemon and its subsystem tests. Earlier
//! C implementations are referenced in module docs only as porting history.
//!
//! ## Current modules
//!
//! - [`engine_loader`] discovers `typio-engine-*.toml` manifests, parses them
//!   with the `toml` crate, negotiates capabilities, and registers
//!   out-of-process engine backends with libtypio.
//! - [`config_watcher`] watches the config directory and engine-manifest
//!   subdirectory via inotify, filters events to relevant files, and debounces
//!   reload triggers with a one-shot timerfd.

// Host Wayland/Flux integration still uses low-level FFI wrappers. Keep the
// Rust 2024 edition migration focused on edition compatibility, not an unsafe
// block audit.
#![allow(unsafe_op_in_unsafe_fn)]

// Auto-generated by build.rs.
pub mod build_info {
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/build_info.rs"));
}

pub mod app;
pub mod boundary;
pub mod candidate_guard;
pub mod config_watcher;
pub mod diagnostics;
pub mod engine_loader;
pub mod focus_controller;
#[cfg(feature = "systray")]
pub mod icon_badge;
pub mod indicator;
#[cfg(feature = "wayland")]
pub use typio_host_platform::{input_method, panel, panel_shm, protocols, text_raster};
pub mod ipc;
pub mod ipc_bus;
pub mod keyboard;
pub mod keyboard_policy;
pub mod language_display;
pub use typio_host_types::{
    panel_coordinator, panel_present_gate, panel_scheduler, wayland_pending,
};
pub mod preedit;
pub mod repeat_timer;
pub mod resume_signal;
pub mod service;
pub mod session_glue;
pub mod state_controller;
pub mod text_ui_state;
#[cfg(feature = "systray")]
pub mod tray_menu;
#[cfg(feature = "systray")]
pub mod tray_menu_ids;
#[cfg(feature = "systray")]
pub mod tray_sni;
pub mod uds_server;
#[cfg(feature = "wayland")]
pub mod voice;
