[package]
name = "typio-daemon"
version = "0.6.1"
description = "Typio Wayland input-method daemon"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "typio"
path = "src/bin/typio.rs"

[features]
default = ["wayland", "systray"]
wayland = ["dep:typio-host-platform", "dep:wayland-client", "dep:wayland-scanner", "dep:wayland-backend", "dep:xkbcommon", "dep:flux-sys", "dep:flux-text-sys", "dep:wayland-sys"]
systray = ["dep:zbus", "dep:flux-sys", "dep:flux-text-sys"]

[dependencies]
wayland-client = { optional = true, version = "0.31" }
wayland-scanner = { workspace = true, optional = true }
wayland-backend = { workspace = true, optional = true }
bitflags.workspace = true
typio-runtime.workspace = true
typio-engine-manifest.workspace = true
typio-host-types = { workspace = true }
typio-host-platform = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
inotify.workspace = true
nix.workspace = true
zbus = { workspace = true, optional = true }
libc.workspace = true
xkbcommon = { workspace = true, optional = true }

flux-sys = { workspace = true, optional = true }
flux-text-sys = { workspace = true, optional = true }
wayland-sys = { workspace = true, optional = true }
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile = "3"
